-- Notify a recruiter once when a waiting registration expires without a match.

create table if not exists public.recruitment_expiry_notify_jobs (
  id bigint generated by default as identity primary key,
  registration_id uuid not null references public.registrations(id) on delete cascade,
  user_id uuid not null,
  area_id text,
  slot text,
  status text not null default 'queued'
    check (status in ('queued','processing','sent','failed','skipped')),
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  locked_at timestamptz,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (registration_id)
);

alter table public.recruitment_expiry_notify_jobs enable row level security;
revoke all on table public.recruitment_expiry_notify_jobs from anon, authenticated;
grant select, insert, update on table public.recruitment_expiry_notify_jobs to service_role;
grant usage, select on sequence public.recruitment_expiry_notify_jobs_id_seq to service_role;

create index if not exists recruitment_expiry_notify_jobs_status_created_idx
  on public.recruitment_expiry_notify_jobs(status, created_at);

create or replace function public.enqueue_recruitment_expiry_notify()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  if old.status = 'waiting'
     and new.status = 'cancelled'
     and new.match_id is null
     and new.expires_at is not null
     and new.expires_at <= now() then
    insert into public.recruitment_expiry_notify_jobs
      (registration_id, user_id, area_id, slot)
    values
      (new.id, new.user_id, new.area_id, new.slot)
    on conflict (registration_id) do nothing;
  end if;
  return new;
end;
$function$;

revoke all on function public.enqueue_recruitment_expiry_notify() from public, anon, authenticated;

drop trigger if exists trg_enqueue_recruitment_expiry_notify on public.registrations;
create trigger trg_enqueue_recruitment_expiry_notify
after update of status on public.registrations
for each row
execute function public.enqueue_recruitment_expiry_notify();

create or replace function public.run_recruitment_expiry_notify_worker()
returns integer
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_expired integer := 0;
  v_request_id bigint;
begin
  v_expired := public.expire_stale_registrations();

  if exists (
    select 1
    from public.recruitment_expiry_notify_jobs
    where (status = 'queued' and attempts < 5)
       or (status = 'processing' and attempts < 5
           and locked_at < now() - interval '5 minutes')
  ) then
    select net.http_get(
      url := 'https://www.nomi-go.jp/api/notify-recruitment-expiry-worker',
      timeout_milliseconds := 10000
    ) into v_request_id;
  end if;

  return v_expired;
end;
$function$;

revoke all on function public.run_recruitment_expiry_notify_worker() from public, anon, authenticated;
grant execute on function public.run_recruitment_expiry_notify_worker() to postgres;

select cron.schedule(
  'notify-expired-recruitments',
  '* * * * *',
  'select public.run_recruitment_expiry_notify_worker();'
);
